const PptxGenJS = require('pptxgenjs');
const path = require('path');
const fs = require('fs');

// Ensure downloads directory exists
const DOWNLOADS_DIR = path.join(__dirname, 'ppt-downloads');
if (!fs.existsSync(DOWNLOADS_DIR)) {
  fs.mkdirSync(DOWNLOADS_DIR, { recursive: true });
}

// Clean old files (older than 1 hour)
function cleanOldFiles() {
  try {
    const files = fs.readdirSync(DOWNLOADS_DIR);
    const now = Date.now();
    files.forEach(file => {
      const filePath = path.join(DOWNLOADS_DIR, file);
      const stat = fs.statSync(filePath);
      if (now - stat.mtimeMs > 3600000) { // 1 hour
        fs.unlinkSync(filePath);
      }
    });
  } catch (e) { /* ignore */ }
}

// Color themes
const THEMES = {
  professional: {
    bg: '0B1120',
    accent: '00D4FF',
    accent2: '7C3AED',
    text: 'F1F5F9',
    subtext: 'A0AEC0',
    gradient: { from: '0B1120', to: '1A1F3A' },
    titleBg: '111827',
  },
  modern: {
    bg: '1E293B',
    accent: '06B6D4',
    accent2: '8B5CF6',
    text: 'F8FAFC',
    subtext: '94A3B8',
    gradient: { from: '0F172A', to: '1E293B' },
    titleBg: '0F172A',
  }
};

/**
 * Parse AI-generated slide content from structured text
 * Expected format from AI:
 * SLIDE 1: Title
 * CONTENT: bullet points or text
 * SLIDE 2: ...
 */
function parseSlideContent(aiResponse) {
  const slides = [];
  
  // Try JSON parse first
  try {
    const jsonMatch = aiResponse.match(/```json\s*([\s\S]*?)```/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[1]);
      if (Array.isArray(parsed.slides || parsed)) {
        return parsed.slides || parsed;
      }
    }
  } catch (e) { /* fall through to text parsing */ }

  // Text-based parsing
  const slideBlocks = aiResponse.split(/(?=SLIDE\s*\d+\s*:)/i);
  
  for (const block of slideBlocks) {
    const titleMatch = block.match(/SLIDE\s*\d+\s*:\s*(.*?)(?:\n|$)/i);
    if (!titleMatch) continue;
    
    const title = titleMatch[1].trim().replace(/\*\*/g, '');
    const contentPart = block.substring(titleMatch[0].length).trim();
    
    // Extract bullet points
    const bullets = [];
    const lines = contentPart.split('\n');
    for (const line of lines) {
      const cleaned = line.replace(/^[-*•]\s*/, '').replace(/\*\*/g, '').trim();
      if (cleaned && !cleaned.match(/^(CONTENT|NOTES|IMAGE|VISUAL):/i) && cleaned.length > 2) {
        bullets.push(cleaned);
      }
    }
    
    slides.push({ title, bullets });
  }
  
  return slides;
}

/**
 * Generate a professional PowerPoint presentation
 */
async function generatePPT(topic, slides, options = {}) {
  cleanOldFiles();
  
  const theme = THEMES.professional;
  const pptx = new PptxGenJS();
  
  // Presentation metadata
  pptx.author = 'MatrixMind AI';
  pptx.company = 'MatrixMind';
  pptx.subject = topic;
  pptx.title = topic;
  pptx.layout = 'LAYOUT_WIDE'; // 13.33 x 7.5 inches
  
  // Define master slides
  pptx.defineSlideMaster({
    title: 'TITLE_SLIDE',
    background: { color: theme.bg },
    objects: [
      // Top accent line
      { rect: { x: 0, y: 0, w: '100%', h: 0.06, fill: { color: theme.accent } } },
      // Bottom gradient bar
      { rect: { x: 0, y: 6.9, w: '100%', h: 0.6, fill: { color: theme.titleBg } } },
      // Branding
      { text: { text: 'Generated by MatrixMind AI', options: { x: 0.5, y: 7.0, w: 4, h: 0.4, fontSize: 9, color: theme.subtext, fontFace: 'Calibri' } } },
    ]
  });
  
  pptx.defineSlideMaster({
    title: 'CONTENT_SLIDE',
    background: { color: theme.bg },
    objects: [
      // Top accent line
      { rect: { x: 0, y: 0, w: '100%', h: 0.04, fill: { color: theme.accent } } },
      // Side accent
      { rect: { x: 0, y: 0.04, w: 0.08, h: 1.2, fill: { color: theme.accent2 } } },
      // Bottom bar
      { rect: { x: 0, y: 7.1, w: '100%', h: 0.4, fill: { color: theme.titleBg } } },
      // Page branding
      { text: { text: 'MatrixMind AI', options: { x: 11, y: 7.15, w: 2, h: 0.3, fontSize: 8, color: theme.subtext, fontFace: 'Calibri', align: 'right' } } },
    ]
  });

  // ==================== SLIDE 1: TITLE SLIDE ====================
  const titleSlide = pptx.addSlide({ masterName: 'TITLE_SLIDE' });
  
  // Large decorative circle
  titleSlide.addShape(pptx.shapes.OVAL, {
    x: 9.5, y: -1, w: 5, h: 5,
    fill: { color: theme.accent, transparency: 90 },
    line: { color: theme.accent, width: 1.5, transparency: 60 }
  });
  
  // Small decorative circle
  titleSlide.addShape(pptx.shapes.OVAL, {
    x: -1, y: 4.5, w: 3, h: 3,
    fill: { color: theme.accent2, transparency: 92 },
    line: { color: theme.accent2, width: 1, transparency: 70 }
  });
  
  // Title
  titleSlide.addText(topic.toUpperCase(), {
    x: 0.8, y: 2.0, w: 11.5, h: 1.8,
    fontSize: 36,
    fontFace: 'Calibri',
    color: theme.text,
    bold: true,
    align: 'left',
    lineSpacingMultiple: 1.1,
  });
  
  // Subtitle line
  titleSlide.addShape(pptx.shapes.RECTANGLE, {
    x: 0.8, y: 3.9, w: 3, h: 0.06,
    fill: { color: theme.accent }
  });
  
  // Subtitle
  titleSlide.addText('Professional Presentation', {
    x: 0.8, y: 4.1, w: 8, h: 0.6,
    fontSize: 18,
    fontFace: 'Calibri',
    color: theme.subtext,
    italic: true
  });
  
  // Date
  titleSlide.addText(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), {
    x: 0.8, y: 4.8, w: 5, h: 0.4,
    fontSize: 12,
    fontFace: 'Calibri',
    color: theme.subtext
  });

  // ==================== CONTENT SLIDES ====================
  for (let i = 0; i < slides.length; i++) {
    const slide = slides[i];
    const contentSlide = pptx.addSlide({ masterName: 'CONTENT_SLIDE' });
    
    // Slide number
    contentSlide.addText(`${String(i + 1).padStart(2, '0')}`, {
      x: 12, y: 0.15, w: 1, h: 0.6,
      fontSize: 24,
      fontFace: 'Calibri',
      color: theme.accent,
      bold: true,
      align: 'right'
    });
    
    // Title
    contentSlide.addText(slide.title, {
      x: 0.5, y: 0.3, w: 11, h: 0.9,
      fontSize: 26,
      fontFace: 'Calibri',
      color: theme.accent,
      bold: true,
    });
    
    // Underline
    contentSlide.addShape(pptx.shapes.RECTANGLE, {
      x: 0.5, y: 1.25, w: 2.5, h: 0.04,
      fill: { color: theme.accent2 }
    });
    
    // Bullet content
    if (slide.bullets && slide.bullets.length > 0) {
      const bulletRows = slide.bullets.map(b => ({
        text: b,
        options: { 
          fontSize: 15, 
          color: theme.text, 
          fontFace: 'Calibri',
          bullet: { type: 'bullet', color: theme.accent },
          lineSpacingMultiple: 1.4,
          paraSpaceAfter: 8,
        }
      }));
      
      contentSlide.addText(bulletRows, {
        x: 0.7, y: 1.5, w: 11.8, h: 5.2,
        valign: 'top',
      });
    }
    
    // Decorative element on right side
    if (i % 2 === 0) {
      contentSlide.addShape(pptx.shapes.ROUNDED_RECTANGLE, {
        x: 12.4, y: 2, w: 0.6, h: 3,
        fill: { color: theme.accent, transparency: 85 },
        rectRadius: 0.3
      });
    }
  }

  // ==================== FINAL SLIDE: THANK YOU ====================
  const endSlide = pptx.addSlide({ masterName: 'TITLE_SLIDE' });
  
  endSlide.addShape(pptx.shapes.OVAL, {
    x: 5, y: 1.5, w: 4, h: 4,
    fill: { color: theme.accent, transparency: 88 },
    line: { color: theme.accent, width: 2, transparency: 50 }
  });
  
  endSlide.addText('Thank You', {
    x: 2, y: 2.5, w: 9, h: 1.5,
    fontSize: 44,
    fontFace: 'Calibri',
    color: theme.text,
    bold: true,
    align: 'center'
  });
  
  endSlide.addText(`Presentation by MatrixMind AI  •  ${topic}`, {
    x: 2, y: 4.2, w: 9, h: 0.6,
    fontSize: 14,
    fontFace: 'Calibri',
    color: theme.subtext,
    align: 'center'
  });

  // ==================== SAVE FILE ====================
  const fileName = `MatrixMind_${topic.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40)}_${Date.now()}.pptx`;
  const filePath = path.join(DOWNLOADS_DIR, fileName);
  
  await pptx.writeFile({ fileName: filePath });
  console.log(`[PPT] Generated: ${fileName} (${slides.length + 2} slides)`);
  
  return { fileName, filePath, slideCount: slides.length + 2 };
}

module.exports = { generatePPT, parseSlideContent, DOWNLOADS_DIR };
