import React from 'react';
import { ArrowLeft, Scale, Shield } from 'lucide-react';

function Legal({ type, onBack }) {
  return (
    <div style={{ width: '100vw', height: '100vh', padding: '40px 20px', overflowY: 'auto', display: 'flex', justifyContent: 'center' }}>
      <div className="glass-panel" style={{ width: '100%', maxWidth: '800px', padding: '40px', position: 'relative', height: 'max-content', marginBottom: '40px' }}>
        <button 
          className="btn btn-secondary" 
          onClick={onBack}
          style={{ position: 'absolute', top: '25px', left: '25px', padding: '8px 16px', display: 'flex', alignItems: 'center', gap: '8px' }}
        >
          <ArrowLeft size={16} /> Back
        </button>

        <div style={{ marginTop: '40px' }}>
          {type === 'tos' ? <TermsOfService /> : <PrivacyPolicy />}
        </div>
      </div>
    </div>
  );
}

function TermsOfService() {
  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '25px' }}>
        <Scale size={32} color="#00f2fe" />
        <h1 style={{ fontFamily: 'Outfit', fontWeight: 800, fontSize: '2rem' }}>Terms of Service</h1>
      </div>
      
      <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', marginBottom: '20px' }}>Last Updated: June 16, 2026</p>

      <section style={sectionStyle}>
        <h3>1. Acceptance of Terms</h3>
        <p>By creating an account, accessing, or using MatrixMind (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service.</p>
      </section>

      <section style={sectionStyle}>
        <h3>2. Age Requirements</h3>
        <p>The Service is intended solely for users who are 18 years of age or older, or minors who have explicit parental or legal guardian consent. Any registration or use of the Service by anyone under these terms is unauthorized.</p>
      </section>

      <section style={sectionStyle}>
        <h3>3. Acceptable Use and Restrictions</h3>
        <p>You explicitly agree NOT to use the Service to:</p>
        <ul style={listStyle}>
          <li>Generate, upload, or share content that is illegal, harmful, threatening, abusive, harassing, defamatory, or promotes violence.</li>
          <li>Generate adult content, sexually explicit materials, or graphic depictions of violence.</li>
          <li>Violate any copyright, trademark, patent, or other proprietary rights of any third party.</li>
          <li>Attempt to compromise the security, reverse engineer, or scrape the data of the Service.</li>
        </ul>
        <p>We reserve the absolute right to monitor activities and immediately ban or terminate accounts that violate these restrictions without prior notice or refund.</p>
      </section>

      <section style={sectionStyle}>
        <h3>4. AI Model and Content Disclaimers</h3>
        <p style={{ color: '#ffa751', fontWeight: 600 }}>WARNING: AI can make mistakes ("hallucinations").</p>
        <p>The answers generated by the AI bot are produced automatically using third-party artificial intelligence engines (specifically Google Gemini). We do not guarantee the correctness, authenticity, completeness, or safety of the generated responses. Users should independently verify any critical information before relying on it. MatrixMind is not responsible or liable for any decisions made based on the bot's outputs.</p>
      </section>

      <section style={sectionStyle}>
        <h3>5. Subscriptions and Refund Policy</h3>
        <p>Subscribing to premium limits (Standard, Better, Premium) is done via direct UPI payment. All fees and subscriptions are billed in advance. **All subscriptions are strictly non-refundable**. Subscriptions do not renew automatically — they expire after the plan duration ends and the user account falls back to the Free tier (30 prompts per day).</p>
      </section>

      <section style={sectionStyle}>
        <h3>6. Limitation of Liability</h3>
        <p>In no event shall MatrixMind, its developers, operators, or affiliates be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the service; (ii) any content generated by the AI bot; or (iii) unauthorized access, use, or alteration of your transmissions or content.</p>
      </section>
    </div>
  );
}

function PrivacyPolicy() {
  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '25px' }}>
        <Shield size={32} color="#00f2fe" />
        <h1 style={{ fontFamily: 'Outfit', fontWeight: 800, fontSize: '2rem' }}>Privacy Policy</h1>
      </div>
      
      <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', marginBottom: '20px' }}>Last Updated: June 16, 2026</p>

      <section style={sectionStyle}>
        <h3>1. Information We Collect</h3>
        <p>We believe in user privacy and collect only the minimum required information to provide the Service:</p>
        <ul style={listStyle}>
          <li><strong>Email Addresses:</strong> Used solely to identify accounts, secure logins, track daily prompt counts, and link active subscription plans.</li>
          <li><strong>Transaction History:</strong> Details of payments processed via UPI (transaction ID, purchase date, plan type, amount) to activate subscription tiers. We do not store credit card or banking details.</li>
        </ul>
        <p><strong>Note:</strong> Chat conversations and histories are stored <strong>locally in the user's browser storage (localStorage)</strong>. We do not send your chat histories to our backend database, ensuring that only you can access and read your conversations.</p>
      </section>

      <section style={sectionStyle}>
        <h3>2. Third-Party Data Sharing</h3>
        <p>To generate chat responses, user prompts and uploaded attachments are processed by third-party AI APIs (specifically Google Gemini). Your inputs are sent to these providers solely for execution. We <strong>do not share or sell</strong> your email, transaction history, or prompt data to any third-party marketing companies, advertisers, or brokers.</p>
      </section>

      <section style={sectionStyle}>
        <h3>3. Secure Cloud Storage</h3>
        <p>We utilize secure file structures and local encrypted database files on our hosting environment to safeguard user profiles, active plan details, and transaction receipts. All network transfers between your device and our backend are secured via standard SSL encryption.</p>
      </section>

      <section style={sectionStyle}>
        <h3>4. Cookies and Local Storage</h3>
        <p>We use browser local storage to persist your active session credentials, active interface themes, and individual chat history blocks. Disabling browser storage will limit the bot's features, including the ability to remember past messages.</p>
      </section>

      <section style={sectionStyle}>
        <h3>5. Contact & Updates</h3>
        <p>We reserve the right to update this policy at any time. Continued use of the Service constitutes agreement to the updated Privacy Policy.</p>
      </section>
    </div>
  );
}

const sectionStyle = {
  marginBottom: '25px'
};

const listStyle = {
  marginLeft: '20px',
  marginTop: '8px',
  marginBottom: '12px',
  color: 'var(--text-muted)',
  fontSize: '0.9rem',
  lineHeight: '1.6'
};

export default Legal;
